In [1]:
import numpy as np
from random import randint

In [2]:
shape = (4,4)
shape

(4, 4)

In [3]:
def create_board(shape):
    board = np.full(shape, 0)

    for i in range(shape[0]):
        for j in range(shape[1]):
            x = randint(0,1)
            if x:
                board[i][j] = 1
    #         print(i, j, x)
#     print(board)
    return board

In [4]:
#line
def count_lines(board, shape):
    count_lines = []
    for i in range(shape[0]):
#         print(board[i])
        count = 0
        count_line = []
        for j in range(shape[1]):
            if board[i][j]:
                count += 1
            if (board[:,j][i] == 0 or j == shape[1]-1) and count != 0:
                count_line.append(count)
                count = 0
        [count_line.append(0) for k in range(int(np.ceil(shape[1]/2)) - len(count_line))]
#         print(count_line)
        count_lines.append(count_line)
#     print(count_lines)
    return count_lines

In [5]:
#row
def count_rows(board, shape):
    count_rows = []
    for j in range(shape[1]):
    #     print(board[:,j])
        count = 0
        count_row = []
        for i in range(shape[0]):
    #         print(board[:,j][i])
            if board[:,j][i]:
                count += 1
            if (board[:,j][i] == 0 or i == shape[0]-1) and count != 0:
                count_row.append(count)
                count = 0
        [count_row.append(0) for k in range(int(np.ceil(shape[0]/2)) - len(count_row))]
    #     print(count_row)
        count_rows.append(count_row)
#     print(count_rows)
    return count_rows

In [6]:
board = create_board(shape)
board

array([[1, 1, 0, 1],
       [0, 1, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 1, 0]])

In [7]:
np.reshape(count_lines(board,shape), (-1))

array([2, 1, 3, 0, 2, 0, 1, 1])

In [8]:
np.reshape(count_rows(board,shape), (-1))

array([1, 1, 3, 0, 3, 0, 2, 0])

In [9]:
import math

In [10]:
shape = (4,4)

max_num = int(math.pow(2,(shape[0]*shape[1])))

data_x = []
data_y = []

for i in range(max_num):
    array = np.array([int(j) for j in format(i,"0"+str(shape[0]*shape[1])+"b")])
    board = array.reshape(shape)
#     print(i, board)
    data_x.append(np.append(np.reshape(count_lines(board,shape), (-1)), np.reshape(count_rows(board,shape), (-1))))
    data_y.append(board)
data_y = np.array(data_y)

In [12]:
np.save("dataset/data_y_4x4", data_y)
np.save("dataset/data_x_4x4", data_x)

In [14]:
data_x = np.load("dataset/data_x_4x4.npy")
data_y = np.load("dataset/data_y_4x4.npy")

In [15]:
print(data_y.shape)
print(data_x.shape)
print(len(np.unique(data_y, axis=0)))
print(len(np.unique(data_x, axis=0)))
print(len(np.unique(data_y, axis=0))-len(np.unique(data_x, axis=0)))

(65536, 4, 4)
(65536, 16)
65536
58196
7340


In [22]:
board = create_board(shape)
x = np.array(np.append(np.reshape(count_lines(board,shape), (-1)), np.reshape(count_rows(board,shape), (-1))))
x = x.reshape((1,-1))
print(x)
print(board)

[[1 0 2 0 1 1 1 1 1 0 1 0 1 0 4 0]]
[[0 0 0 1]
 [0 0 1 1]
 [0 1 0 1]
 [1 0 0 1]]


In [18]:
from keras.models import load_model

Using TensorFlow backend.


In [23]:
model = load_model('model_4x4.h5')

pred = model.predict(x/shape[0])
np.round((pred+1)/2)[0]

array([[0., 0., 0., 1.],
       [0., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 1., 0., 1.]], dtype=float32)